window.GEAR_ITEMS = [
  { id: 'i01', name: 'Canon EOS Rebel T7 DSLR Camera with 18-55mm Lens', category: 'Camera', qty: 1, status: 'available', brand: 'Canon', model: 'EOS Rebel T7', serial: 'CR7-2284-A', value: 549, location: 'Shelf A1' },
  { id: 'i02', name: 'Lumens VC-A51 20x DVI-I/3G-SDI HD PTZ Camera', category: 'Camera', qty: 2, status: 'available', brand: 'Lumens', model: 'VC-A51', serial: 'LM-A51-0091', value: 3200, location: 'Cabinet B' },
  { id: 'i03', name: 'FUJIFILM X-Pro2 Mirrorless Digital Camera', category: 'Camera', qty: 1, status: 'checked-out', brand: 'Fujifilm', model: 'X-Pro2', serial: 'FX-PRO-7741', value: 1499, location: 'Out' },
  { id: 'i04', name: 'Panasonic Lumix DC-GH5S Mirrorless Camera', category: 'Camera', qty: 1, status: 'available', brand: 'Panasonic', model: 'DC-GH5S', serial: 'PL-GH5S-0042', value: 2197, location: 'Shelf A2' },
  { id: 'i05', name: 'RED Digital Cinema V-RAPTOR 8K S35 Production Pack', category: 'Cinema', qty: 1, status: 'available', brand: 'RED', model: 'V-RAPTOR 8K', serial: 'RD-VR-8K-0014', value: 24500, location: 'Vault' },
  { id: 'i06', name: '5" Half Single Scrim', category: 'Lighting', qty: 4, status: 'available', brand: 'Matthews', model: 'Half Single', serial: '—', value: 35, location: 'Grip Cart' },
  { id: 'i07', name: 'Canon VIXIA HF W10 Waterproof Camcorder', category: 'Camera', qty: 1, status: 'available', brand: 'Canon', model: 'VIXIA HF W10', serial: 'CV-W10-1188', value: 599, location: 'Shelf A3' },
  { id: 'i08', name: 'Lumens Ladibug DC193 HD Document Camera', category: 'Camera', qty: 1, status: 'available', brand: 'Lumens', model: 'DC193', serial: 'LD-193-0288', value: 449, location: 'Shelf C1' },
  { id: 'i09', name: 'Lumens VC-BC701PB 4Kp60 Box Cam 30x', category: 'Camera', qty: 1, status: 'maintenance', brand: 'Lumens', model: 'VC-BC701PB', serial: 'LM-BC7-0033', value: 2899, location: 'Repair' },
  { id: 'i10', name: 'Panasonic Lumix DC-S1R with 24-105mm Lens', category: 'Camera', qty: 1, status: 'available', brand: 'Panasonic', model: 'DC-S1R', serial: 'PL-S1R-9921', value: 3699, location: 'Shelf A2' },
  { id: 'i11', name: 'DJI Ronin 4D Camera Monitor', category: 'Monitor', qty: 1, status: 'available', brand: 'DJI', model: 'Ronin 4D', serial: 'DJ-R4D-0451', value: 1099, location: 'Cabinet B' },
  { id: 'i12', name: 'Aputure 600d Pro LED Light Kit', category: 'Lighting', qty: 2, status: 'available', brand: 'Aputure', model: '600d Pro', serial: 'AP-600-2210', value: 1890, location: 'Light Truck' },
  { id: 'i13', name: 'G-Technology G-RAID Shuttle SSD 16TB', category: 'Storage', qty: 3, status: 'available', brand: 'G-Tech', model: 'Shuttle SSD', serial: 'GT-SH-16-A', value: 2499, location: 'DIT Cart' },
  { id: 'i14', name: 'Tilta Camera Cage for Sony FX6', category: 'Rigging', qty: 1, status: 'available', brand: 'Tilta', model: 'FX6 Cage', serial: 'TL-FX6-0019', value: 339, location: 'Shelf B2' },
  { id: 'i15', name: 'NiSi Athena Prime 18mm T2.2 Cinema Lens', category: 'Lens', qty: 1, status: 'available', brand: 'NiSi', model: 'Athena 18mm', serial: 'NS-AT18-0007', value: 1499, location: 'Lens Drawer' },
  { id: 'i16', name: 'Sennheiser MKH 416 Shotgun Microphone', category: 'Audio', qty: 2, status: 'available', brand: 'Sennheiser', model: 'MKH 416', serial: 'SN-416-2241', value: 999, location: 'Sound Cart' },
  { id: 'i17', name: 'SmallHD 702 Touch 7" On-Camera Monitor', category: 'Monitor', qty: 1, status: 'available', brand: 'SmallHD', model: '702 Touch', serial: 'SH-702-0312', value: 1699, location: 'Shelf B3' },
  { id: 'i18', name: 'DJI RS 3 Pro 3-Axis Gimbal Stabilizer', category: 'Rigging', qty: 1, status: 'available', brand: 'DJI', model: 'RS 3 Pro', serial: 'DJ-RS3-1180', value: 869, location: 'Cabinet C' },
];
